import type { ConceptAnnotation, Medication } from "./types";

export const medications: Medication[] = [
  {
    id: "wegovy-pill",
    name: "Wegovy Pill",
    type: "Pill",
    generic: "Semaglutide",
    firstMonth: 149,
    ongoing: 249,
    prepay3: 229,
    prepay12: 199,
    badge: "Lowest first-month price",
    cadence: "Daily",
    insurance: "May be eligible",
    approval: "Clinician review",
    why: "A daily routine with the lowest first-month price.",
  },
  {
    id: "wegovy-pen",
    name: "Wegovy Pen",
    type: "Injection",
    generic: "Semaglutide",
    firstMonth: 199,
    ongoing: 249,
    prepay3: 229,
    prepay12: 199,
    badge: "Same long-term price as pill",
    cadence: "Usually weekly",
    insurance: "May be eligible",
    approval: "Clinician review",
    why: "A familiar weekly format with the same ongoing price as the pill.",
  },
  {
    id: "zepbound-kwikpen",
    name: "Zepbound KwikPen",
    type: "Injection",
    generic: "Tirzepatide",
    firstMonth: 199,
    ongoing: 299,
    prepay3: 279,
    prepay12: 249,
    badge: "Popular",
    cadence: "Usually weekly",
    insurance: "May be eligible",
    approval: "Clinician review",
    why: "A popular weekly option with several commitment lengths.",
  },
  {
    id: "zepbound-vial",
    name: "Zepbound Vial",
    type: "Injection",
    generic: "Tirzepatide",
    firstMonth: 149,
    ongoing: 299,
    prepay3: 279,
    prepay12: 249,
    badge: "Lower starter cost",
    cadence: "Usually weekly",
    insurance: "Self-pay common",
    approval: "Clinician review",
    why: "A lower starter cost for people comfortable using a vial.",
  },
  {
    id: "found-pill",
    name: "Found Pill",
    type: "Pill",
    generic: "Orforglipron",
    firstMonth: 149,
    ongoing: 199,
    badge: "Daily pill",
    cadence: "Daily",
    insurance: "Self-pay",
    approval: "Clinician review",
    why: "A daily pill with the lowest typical ongoing price.",
  },
  {
    id: "ozempic",
    name: "Ozempic",
    type: "Injection",
    generic: "Semaglutide",
    firstMonth: 249,
    ongoing: 349,
    badge: "Clinician approval required",
    cadence: "Usually weekly",
    insurance: "May be eligible",
    approval: "Required",
    why: "An established option your clinician may consider when appropriate.",
  },
];

export const supportingCopy =
  "Your clinician will review your health history and preferences before prescribing. Final medication and pricing may depend on your clinical assessment.";

export const disclaimer =
  "Medication pricing is separate from the Maven membership unless otherwise stated.";

export const annotations: ConceptAnnotation[] = [
  {
    label: "Current design",
    name: "Current design reference",
    technique: "Familiarity and recognition",
    hypothesis: "A restrained list keeps clinical choice feeling calm and familiar.",
    risk: "Starting prices can obscure what members pay later.",
    metric: "Pricing-detail engagement",
  },
  {
    label: "Concept 1",
    name: "Cost-first cards",
    technique: "Anchoring and information prioritisation",
    hypothesis: "Leading with the first-month price makes comparison faster.",
    risk: "Members may overweight the starter price.",
    metric: "Drug-selection completion",
  },
  {
    label: "Concept 2",
    name: "Minimal pricing",
    technique: "Progressive disclosure",
    hypothesis: "Daily pricing lowers visual complexity while a sheet holds the full truth.",
    risk: "Some members may never open the full pricing sheet.",
    metric: "Pricing-detail engagement",
  },
  {
    label: "Concept 3",
    name: "Format first",
    technique: "Choice architecture and chunking",
    hypothesis: "Choosing pill or injection first reduces cognitive load.",
    risk: "Format-first framing may hide a better-fit alternative.",
    metric: "Drug-selection completion",
  },
  {
    label: "Concept 4",
    name: "Cost timeline",
    technique: "Expectation setting",
    hypothesis: "A month-by-month timeline reduces future price surprise.",
    risk: "Dense timelines may slow scanning.",
    metric: "Immediate cancellation rate",
  },
  {
    label: "Concept 5",
    name: "Three-month preview",
    technique: "Mental accounting and total-cost framing",
    hypothesis: "A near-term total supports more realistic budgeting.",
    risk: "The higher total can feel intimidating.",
    metric: "Checkout conversion",
  },
  {
    label: "Concept 6",
    name: "Comparison table",
    technique: "Attribute-based decision making",
    hypothesis: "Aligned attributes help members make deliberate trade-offs.",
    risk: "Comparison mode can amplify decision fatigue.",
    metric: "Drug-selection completion",
  },
  {
    label: "Concept 7",
    name: "Price accordion",
    technique: "Low-disruption progressive disclosure",
    hypothesis: "A familiar card list can hold complete pricing without a redesign shock.",
    risk: "Important costs remain one tap away.",
    metric: "Pricing-detail engagement",
  },
  {
    label: "Concept 8",
    name: "Confidence-led recommendation",
    technique: "Social proof and reassurance",
    hypothesis: "Suitability cues reduce anxiety before price comparison.",
    risk: "Badges may be mistaken for clinical recommendations.",
    metric: "Account creation conversion",
  },
  {
    label: "Concept 9",
    name: "Interactive calculator",
    technique: "Control and uncertainty reduction",
    hypothesis: "A tailored estimate gives price-sensitive members confidence.",
    risk: "More inputs may create friction or false precision.",
    metric: "Pricing-related support contacts",
  },
  {
    label: "Concept 10",
    name: "Transparency promise",
    technique: "Trust signalling and differentiation",
    hypothesis: "Leading with pricing honesty positions Maven as a safer choice.",
    risk: "Trust language can feel promotional if overworked.",
    metric: "Day-7 retained membership",
  },
];

export const money = (amount: number) => `$${amount}`;
export const dailyPrice = (amount: number) => `$${(amount / 30).toFixed(2)}`;
export const firstThreeMonthTotal = (medication: Medication) =>
  medication.firstMonth * 2 + medication.ongoing;
